Remove native libraries
vignette-project/vignette pull request #82
Opened 2020-10-20 23:47 UTC by LeNitrous

We'll be using a different method of obtaining the dependencies. See https://github.com/vignette-project/osu-framework-live2d/pull/42.

2020-10-21 08:32 UTC, sr229 approved these changes

2020-10-21 23:39 UTC, sr229 reviewed
You'll need to have the new fetching mechanism here then I can merge it to prevent CI failures.

2020-10-23 09:50 UTC, sr229 requested changes

2020-10-23 09:50 UTC, sr229 commented on .github/workflows/deploy-stable.yml
> +          content: "Hey @everyone! This is your local Insider messenger! This is a test message for Discord-based alerts. If you see something like this in the near future, check the Appcenter!"
Looks like this was unintentionally reverted.

2020-11-02 10:57 UTC, sr229 commented
Closing since it's inactive, feel free to reopen when you get to it again.

2020-11-02 11:28 UTC, LeNitrous commented
@sr229 just need this one out and we can get started with the UX rewrite

2020-11-02 16:25 UTC, merged